variables:
  LATEST_VER: batlefroc/akaucore:latest
  CURRENT_VER: batlefroc/akaucore:1.1
  CONTAINER_NAME: akaucore
  WEBHOOK_URL: "https://discordapp.com/api/webhooks/735175356054765618/MdOM3hDJPPEi1HBnCDJWhPQNK78-dOShV_mbu2dR4PfQfUZd_m0T3AMff670UMgqKCr4"

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - lint
  - build
  - stopOld
  - run
  - hook
  - test

Lint: 
  stage: lint
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  allow_failure: true
  tags:
    - kimsufi
  script:
    - dotnet tool update -g dotnet-format
    - dotnet format --check

Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  tags: 
    - kimsufi
  script:
    - docker build -t $LATEST_VER -t $CURRENT_VER .

StopOld:
  stage: stopOld
  image: docker:latest
  allow_failure: true
  tags: 
    - kimsufi
  needs:
    - Build
  script:
    - docker container stop $CONTAINER_NAME
    - docker container rm $CONTAINER_NAME

Run:
  stage: run
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  tags: 
    - kimsufi
  needs:
    - Build
  script : 
    - docker run -d --network weebo --name $CONTAINER_NAME -p 8082:80 $LATEST_VER

Hook:
  stage: hook
  image: ubuntu
  allow_failure: true
  tags:
    - kimsufi
  needs:
    - Run
  script:
    - apt update
    - apt install curl -y
    - apt install wget -y
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL

Test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  allow_failure: true
  tags:
    - kimsufi
  script:
    - dotnet test ./TestLibrary/3.TestLibrary.csproj --blame-hang-timeout 30s --logger "console;verbosity=detailed"

code_quality:
  stage: test
  artifacts:
    paths: [gl-code-quality-report.json]